### ISSUE TITLE
how prometheus get dcgm-exporter metrics?

### ISSUE THREAD

**Issue by Leteong** [NVIDIA/gpu-monitoring-tools#106]
Now, I use endpoints ip:port 

example:
static_configs:
- targets: [ ""10.244.1.28:9400" ]
If endpoints changes, I can't get metrics,  What should I do ?

**Comment by robbo10** [comment]
Have you got the service monitor installed?

**Comment by wacken89** [comment]
If you use prometheus server not operator, then you can add `annotations` to pods

```yaml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "dcgm-exporter"
        app.kubernetes.io/version: "2.0.0-rc.12"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9400'
```

**Comment by Leteong** [comment]
> If you use prometheus server not operator, then you can add `annotations` to pods
> 
> ```yaml
>   template:
>     metadata:
>       labels:
>         app.kubernetes.io/name: "dcgm-exporter"
>         app.kubernetes.io/version: "2.0.0-rc.12"
>       annotations:
>         prometheus.io/scrape: 'true'
>         prometheus.io/port: '9400'
> ```

Thank you so much

**Comment by samuelthan** [comment]
Hi,

- Cloud Environment: AWS-EKS version 1.17.3
- Prometheus-Operator Stack latest version at https://github.com/prometheus-community/helm-charts

I'm following the instructions as per https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#setting-up-dcgm

Am having same trouble of not able to scrape DCGM exporter metrics.

Am i right to assume i have to additionally add those scraping config even for prometheus-operator ?

**Comment by westfly** [comment]
> Hi,
> 
> * Cloud Environment: AWS-EKS version 1.17.3
> * Prometheus-Operator Stack latest version at https://github.com/prometheus-community/helm-charts
> 
> I'm following the instructions as per https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#setting-up-dcgm
> 
> Am having same trouble of not able to scrape DCGM exporter metrics.
> 
> Am i right to assume i have to additionally add those scraping config even for prometheus-operator ?

I use [dcgm-exporter](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/dcgm-exporter.yaml) instead of helm-char 
add annotations param
```
kind: Service
apiVersion: v1
metadata:
  name: "dcgm-exporter"
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.0"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
    prometheus.io/path: "metrics"
spec:
  selector:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.0"
  ports:
  - name: "gpu-metrics"
    port: 9400

```

**Comment by ndtreviv** [comment]
> Hi,
> 
> * Cloud Environment: AWS-EKS version 1.17.3
> * Prometheus-Operator Stack latest version at https://github.com/prometheus-community/helm-charts
> 
> I'm following the instructions as per https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#setting-up-dcgm
> 
> Am having same trouble of not able to scrape DCGM exporter metrics.
> 
> Am i right to assume i have to additionally add those scraping config even for prometheus-operator ?

I had to do this using the operator.
In the end I had to not use the dcgm-exporter helm chart (because it wasn't working for me anyway - getting stuck in a CrashLoopBackoff), instead I grabbed the source from the helm chart repo and modified it to become this config:

```
apiVersion: v1
kind: Namespace
metadata:
  name: dcgm-exporter
  labels:
    name: dcgm-exporter
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "dcgm-exporter"
  namespace: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "dcgm-exporter"
      app.kubernetes.io/version: "2.3.1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "dcgm-exporter"
        app.kubernetes.io/version: "2.3.1"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9400"
      name: "dcgm-exporter"
    spec:
      containers:
      - image: "nvcr.io/nvidia/k8s/dcgm-exporter:2.1.4-2.3.1-ubuntu18.04"
        env:
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        name: "dcgm-exporter"
        ports:
        - name: "metrics"
          containerPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add:
              - "SYS_ADMIN"
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"

---

kind: Service
apiVersion: v1
metadata:
  name: "dcgm-exporter"
  namespace: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
spec:
  selector:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
  ports:
  - name: "metrics"
    port: 9400
```

The namespace is important here.

Then I installed the prometheus stack from helm like this:
```
helm install prometheus-community/kube-prometheus-stack \
--create-namespace --namespace prometheus \
--generate-name \
--values ./kube-prometheus-stack.values
```

The values I got from the chart using helm inspect, as per the nvidia docs, and added the following scraper job config:

```
    additionalScrapeConfigs:
    - job_name: gpu-metrics
      scrape_interval: 1s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - dcgm-exporter
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node
```

et voila, it worked. What the nvidia docs fail to tell you is that you need to install the dgcm-exporter under the namespace they're targeting in their config, which they've called:

```
      - gpu-operator-resources
```
BUT again, if you follow their instructions and install the dcgm-exporter from helm, it doesn't get put under that namespace automatically, so it just doesn't work.

Hope this helps someone else!

**Comment by aii-shanker-jj** [comment]
I have used helm to deploy dcgm-exporter & used `additionalScrapeConfigs:` mentioned by @ndtreviv to apply `kube-prometheus-stack`.

@ndtreviv if I install dcgm-exporter in the samenamespace as  `kube-prometheus-stack`, what would be the change under ` kubernetes_sd_configs:`. Any suggestions.

**Comment by shan100github** [comment]
I have added taint to GPU nodes & used helm to deploy `dcgm-exporter` along with the below toleration as values for helm command as `helm install dcgm-exporter gpu-helm-charts/dcgm-exporter -n dcgm-exporter  -f values.yaml` .

```
tolerations:
  - key: "key"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
```
 used `additionalScrapeConfigs:` mentioned by @ndtreviv to apply `kube-prometheus-stack`.

@ndtreviv if I install `dcgm-exporter` in the same namespace as  `kube-prometheus-stack`, what would be the change under ` kubernetes_sd_configs:`. Any suggestions.

**Comment by Leteong** [comment]
thanks

**Comment by JulesBelveze** [comment]
Hey @ndtreviv I'm trying to setup DCGM on GKE. I followed the steps [here](https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#install-kubernetes) and I'm also not able to seeing the DCGM in Prometheus.

Following your suggestions I have installed the NVIDIA device plugin (everything went well). However, I tried to use your `dcgm-exporter.yaml` file but my pods get stuck to `CrashLoopBackOff`, the logs gave me the following:
```
time="2021-04-22T07:11:36Z" level=info msg="Starting dcgm-exporter"
Error: Failed to initialize NVML
time="2021-04-22T07:11:36Z" level=fatal msg="Error starting nv-hostengine: DCGM initialization error"
```
Any idea what could have gone wrong?

It really seems to be a version mismatch cause the following `dcgm-exporter.yaml` didn't give me any error:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.1.1"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "dcgm-exporter"
      app.kubernetes.io/version: "2.1.1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "dcgm-exporter"
        app.kubernetes.io/version: "2.1.1"
      name: "dcgm-exporter"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
      containers:
      - image: "nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04"
        env:
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        name: "dcgm-exporter"
        ports:
        - name: "metrics"
          containerPort: 9400
        securityContext:
          privileged: true
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
        - name: "nvidia-install-dir-host"
          mountPath: "/usr/local/nvidia"
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"
      - name: "nvidia-install-dir-host"
        hostPath:
          path: "/home/kubernetes/bin/nvidia"
---

kind: Service
apiVersion: v1
metadata:
  name: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.1.1"
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9400'
    prometheus.io/path: 'metrics'
spec:
  selector:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.1.1"
  ports:
  - name: "metrics"
    port: 9400
```

Thanks for your help, really having a hard time on this one 😅

**Comment by JulesBelveze** [comment]
@Leteong only adding the `annotations` worked in your case?

**Comment by ndtreviv** [comment]
> @ndtreviv if I install `dcgm-exporter` in the same namespace as `kube-prometheus-stack`, what would be the change under ` kubernetes_sd_configs:`. Any suggestions.

You can see my full process here: https://stackoverflow.com/questions/65076998/how-to-scale-azures-kubernetes-service-aks-based-on-gpu-metrics/66798158#66798158

My `kubernetes_sd_configs` looked like so:
```
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - my-namespace
```
Where `my-namespace` was the namespace with the dcgm-exporter AND HPA in (and therefore the service being scaled by the HPA)

**Comment by ndtreviv** [comment]
> Hey @ndtreviv I'm trying to setup DCGM on GKE. I followed the steps [here](https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#install-kubernetes) and I'm also not able to seeing the DCGM in Prometheus.
> 
> Following your suggestions I have installed the NVIDIA device plugin (everything went well). However, I tried to use your `dcgm-exporter.yaml` file but my pods get stuck to `CrashLoopBackOff`, the logs gave me the following:
> 
> ```
> time="2021-04-22T07:11:36Z" level=info msg="Starting dcgm-exporter"
> Error: Failed to initialize NVML
> time="2021-04-22T07:11:36Z" level=fatal msg="Error starting nv-hostengine: DCGM initialization error"
> ```
> 
> Any idea what could have gone wrong?
> Thanks for your help, really having a hard time on this one 😅

Yeah, sorry, I had to add a couple of other missing parts. It ended up looking like this:

```
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
  labels:
    name: dcgm-exporter
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "dcgm-exporter"
  namespace: "my-namespace"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "dcgm-exporter"
      app.kubernetes.io/version: "2.3.1"
      app.kubernetes.io/component: "dcgm-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "dcgm-exporter"
        app.kubernetes.io/version: "2.3.1"
        app.kubernetes.io/component: "dcgm-exporter"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9400"
      name: "dcgm-exporter"
    spec:
      serviceAccountName: dcgm-exporter
      containers:
      - image: myorg.azurecr.io/dcgm-exporter:2.1.4-2.3.1-ubuntu18.04
      # - image: "nvcr.io/nvidia/k8s/dcgm-exporter:2.1.4-2.3.1-ubuntu18.04"
        env:
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        name: "dcgm-exporter"
        ports:
        - name: "metrics"
          containerPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add:
              - "NET_ADMIN"
              - "NET_RAW"
              - "SYS_ADMIN"
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"

---
kind: Service
apiVersion: v1
metadata:
  name: "dcgm-exporter"
  namespace: "my-namespace"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
    app.kubernetes.io/component: "dcgm-exporter"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
  ports:
  - name: "metrics"
    port: 9400
    targetPort: 9400
    protocol: TCP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: "my-namespace"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
    app.kubernetes.io/component: "dcgm-exporter"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "dcgm-exporter"
  namespaceSelector:
    matchNames:
    - "my-namespace"
  endpoints:
  - port: "metrics"
    path: "/metrics"
    interval: 15s

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcgm-exporter
  namespace: "my-namespace"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.3.1"
    app.kubernetes.io/component: "dcgm-exporter"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
```

It took me so long to get this right. Take a look here for my full process: https://stackoverflow.com/questions/65076998/how-to-scale-azures-kubernetes-service-aks-based-on-gpu-metrics/66798158#66798158
