### ISSUE TITLE
exported_pod field not available on GKE cluster (but available on AWS)

### ISSUE THREAD

**Issue by RobertLucian** [NVIDIA/gpu-monitoring-tools#160]
#### Version

EKS/GKE 1.18

#### Description

Assuming the following DCGM exporter

<details>
<summary>Click to the DCGM exporter config!</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcgm-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/component: dcgm-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/component: dcgm-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
      app.kubernetes.io/instance: dcgm-exporter
      app.kubernetes.io/component: dcgm-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dcgm-exporter
        app.kubernetes.io/instance: dcgm-exporter
        app.kubernetes.io/component: dcgm-exporter
    spec:
      serviceAccountName: dcgm-exporter
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu
                operator: Exists
      containers:
      - env:
        - name: DCGM_EXPORTER_LISTEN
          value: :9400
        - name: DCGM_EXPORTER_KUBERNETES
          value: "true"
        image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
        imagePullPolicy: Always
        name: dcgm-exporter
        ports:
        - containerPort: 9400
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/pod-resources
          name: pod-gpu-resources
          readOnly: true
        - mountPath: /usr/local/nvidia
          name: nvidia-install-dir-host
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: workload
        effect: NoSchedule
        operator: Exists
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pod-resources
          type: ""
        name: pod-gpu-resources
      - hostPath:
          path: /home/kubernetes/bin/nvidia
          type: ""
        name: nvidia-install-dir-host
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dcgm-exporter
  namespace: default
  labels:
    monitoring.cortex.dev: dcgm-exporter
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/component: dcgm-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9400'
spec:
  jobLabel: "dcgm-exporter"
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 15s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
      app.kubernetes.io/instance: dcgm-exporter
```
</details>

It looks like on EKS, the `exported_pod` label is available to any of the exported metrics. But when I use the same config on GKE, the `exported_pod` label is no longer there. The `exported_pod` label is a label that indicates which pod has actually requested the resource.

Here is an example of the labels exposed on GKE:

![Screenshot 2021-03-01 at 21.30.59.png](https://images.zenhubusercontent.com/59199cd851aa2c30577e4ba4/38c9ea94-9ddf-4d96-a363-9deb6b9ea313)

I don't have a screenshot at hand for the one on AWS, but if you request it, I can attach it as well.

#### Resolution

Does anyone know if there's an annotation/config missing for the GKE cluster? Or if this is a bug?
