### ISSUE TITLE
How do I mount a custom csv file with Kubernetes ?

### ISSUE THREAD

**Issue by dmrub** [NVIDIA/gpu-monitoring-tools#169]
I want to enable the `DCGM_FI_DEV_GPU_UTIL` metric and want to add a custom csv file to the Kubernetes ConfigMap and then mount it. There is a helm option `extraVolumeMounts` to mount and `arguments` options to specify alternate filenames for loading csv file. However, there is no option to define the ConfigMap volume or. Only the `extraHostVolumes` option for `hostVolume` is present.

**Comment by shan100github** [comment]
When is this going to get merged.

**Comment by shan100github** [comment]
@dmrub temporarily I did build a dcgm-exporter image with `DCGM_FI_DEV_GPU_UTIL` enabled and its in docker hub.
`shan100docker/dcgm-exporter:2.1.8-2.4.0-rc.2-ubuntu18.04-v2`

Feel free to use it if necessary.
Also make sure to pass below as values.yaml & use  `helm install dcgm-exporter gpu-helm-charts/dcgm-exporter -n <NAMESPACE>  -f values.yaml`
```
image:
  repository: shan100docker/dcgm-exporter
  pullPolicy: IfNotPresent
  tag: 2.1.8-2.4.0-rc.2-ubuntu18.04-v2

arguments: ["-f", "/etc/dcgm-exporter/dcp-metrics-included.csv"]
```
