### ISSUE TITLE
dcgm-exporter failed on CPU node 

### ISSUE THREAD

**Issue by dkozlov** [NVIDIA/gpu-monitoring-tools#6]
Hi, I think dcgm-exporter should not fail on CPU nodes. My usecase is following: I am using standard https://github.com/coreos/prometheus-operator and want to use same node-exporter yaml for all kubernetes nodes
```kubectl logs dcgm-exporter-daemonset-fhccr -c dcgm-exporter
Starting NVIDIA host engine...
Collecting metrics at /run/prometheus/dcgm.prom every 1000ms...
/usr/local/bin/dcgm-exporter: line 55: nvidia-smi: command not found
Stopping NVIDIA host engine...
Unable to terminate host engine, it may not be running.
/usr/local/bin/dcgm-exporter: line 143: kill: (22212) - No such process
Done```

**Comment by guptaNswati** [comment]
There is no good solution for this right now. You can have two version of node-exporters, one with dcgm-exporter and your original. Then you can control deploying dcgm-exporter only on GPU nodes using NodeSelectors.

**Comment by dkozlov** [comment]
I have found workaround:
```
      containers:
      - name: dcgm-exporter
        image: nvidia/dcgm-exporter
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do dcgm-exporter -e; sleep 30; done;"]
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: collector-textfiles
          mountPath: /run/prometheus
          readOnly: false
```
But it would be nice to fix this behaviour
